# Generated by Django 6.0.7 on 2026-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_a', models.CharField(max_length=255)),
                ('col_b', models.CharField(max_length=255)),
                ('col_c', models.CharField(max_length=255)),
                ('col_d', models.CharField(max_length=255)),
            ],
        ),
    ]
