# Generated by Django 6.0.7 on 2026-07-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightweightExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
    ]
